version: '3.9'

services:

  todo-backend:
    image: todo-backend
    container_name: todo-backend
    depends_on:
      - todo-db
    restart: "no"
    ports:
      - 8080:8080
    build:
      context: .
    environment:
      DATABASE_URL: "postgres://todo_dba:v8!oGS,MLFk2@todo-db:5432/todo"
      DB_SSL_MODE: "disable"

  todo-db:
    image: postgres:14.1-bullseye
    container_name: todo-db
    restart: "no"
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: "todo_dba"
      POSTGRES_PASSWORD: "v8!oGS,MLFk2"
      POSTGRES_DB: "todo"
